"""addClassPermissions1

Revision ID: b26ef8d280a1
Revises: 
Create Date: 2025-04-21 14:50:14.356020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b26ef8d280a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classPermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=200), nullable=True),
    sa.Column('class_menagers_email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classPermission_id'), 'classPermission', ['id'], unique=False)
    op.drop_index('ix_classPermission_id', table_name='classpermission')
    op.drop_table('classpermission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classpermission',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('class_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('class_menagers_email', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_classPermission_id', 'classpermission', ['id'], unique=False)
    op.drop_index(op.f('ix_classPermission_id'), table_name='classPermission')
    op.drop_table('classPermission')
    # ### end Alembic commands ###
